### ISSUE TITLE
Consistent behavior with no data 

### ISSUE THREAD

**Issue by ujovlado** [keboola/php-csvmap#3]
Ked si napisem mapping, ktory sa snazi vytiahnut data z neexistujucich "ciest" subor je vytvoreny a bude v nom len prvy riadok (hlavicka).

Ked toto iste spravim s relacnou tabulkou, subor vytvoreny nie je a `$parser->getCsvFiles()` ma jednu polozku `null`.

Mapping sample:

``` yaml
mapping:
  one.$oid:
    type: column
    mapping:
      destination: id
      primaryKey: true
  two:
      type: table
      destination: test-two
      parentKey:
        destination: one_id
      tableMapping:
        column:
    type: column
    mapping:
      destination: column
      primaryKey: true
```

Myslim, ze chovanie by malo byt konzistentne.  Cize bud nech tie subory vytvara stale, alebo ked nie su data, nech ich nevytvara vobec. Momentalne vytvara len tie z prvej urovne.
